import { useEffect, useState, type FormEvent } from 'react';
import type { DocumentMeta, QaAnswer } from '../shared/types';

export function App() {
  const [documents, setDocuments] = useState<DocumentMeta[]>([]); const [question, setQuestion] = useState(''); const [result, setResult] = useState<QaAnswer>(); const [busy, setBusy] = useState(false); const [dataDirectory, setDataDirectory] = useState('');
  const refresh = async () => setDocuments(await window.knowledgeBase.documents.list());
  useEffect(() => { void refresh(); void window.knowledgeBase.system.dataDirectory().then(setDataDirectory); }, []);
  const importDocuments = async () => { await window.knowledgeBase.documents.import(); await refresh(); };
  const ask = async (event: FormEvent) => { event.preventDefault(); if (!question.trim() || busy) return; setBusy(true); try { setResult(await window.knowledgeBase.qa.ask(question.trim())); } finally { setBusy(false); } };
  return <div className="app"><header><div className="brand"><span className="logo">L</span><div><h1>LumenVault</h1><p>你的本地知识库</p></div></div><button className="ghost" onClick={() => void refresh()}>刷新</button></header><main><aside><div className="aside-title"><span>文档</span><b>{documents.length}</b></div><button className="import" onClick={() => void importDocuments()}>＋ 导入文档</button><div className="documents">{documents.length === 0 ? <div className="empty"><span>◇</span><strong>还没有文档</strong><p>导入 .txt 或 .md 文件<br/>开始构建知识库</p></div> : documents.map((document) => <article key={document.id}><div className="file-icon">文</div><div><strong>{document.title}</strong><small>{Math.max(1, Math.round(document.size / 1024))} KB · 已索引</small></div><button title="删除" onClick={async () => { await window.knowledgeBase.documents.delete(document.id); await refresh(); }}>×</button></article>)}</div></aside><section className="qa"><div className="welcome"><span className="spark">✦</span><h2>向你的知识库提问</h2><p>答案仅基于你导入的本地文档，并附带来源引用。</p></div>{result && <div className="answer"><div className="answer-title">回答 <span>{Math.round(result.confidence * 100)}% 置信度</span></div><p>{result.answer}</p>{result.citations.map((citation) => <blockquote key={citation.documentId + citation.excerpt}><b>{citation.title}</b><br/>{citation.excerpt}</blockquote>)}</div>}<form onSubmit={(event) => void ask(event)}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="输入你的问题…"/><button disabled={busy || !question.trim()}>{busy ? '检索中' : '提问 →'}</button></form></section></main><footer><span><i/> 本地存储已就绪</span><span title={dataDirectory}>{dataDirectory}</span></footer></div>;
}
